server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native   #本地路劲
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared/
